server:
  port: ${SERVER_PORT}
spring:
  h2:
    console:
      enabled: true
  mail:
    host: ${MAIL_HOST}
    username: hello
    password: hello
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          ssl:
            trust: '*'
          starttls:
            enable: true
          timeout: 3000
          writetimeout: 5000
    
